In [5]:
import pandas as pd
import numpy as np
from scipy import stats

# **Load Data**

In [11]:
df_control = pd.read_csv('control_group.csv' , sep=';')
df_test = pd.read_csv('test_group.csv' , sep=';')

In [12]:
df_control.head()
df_control.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign Name        30 non-null     object
 1   Date                 30 non-null     object
 2   Spend [USD]          30 non-null     int64
 3   # of Impressions     29 non-null     float64
 4   Reach                29 non-null     float64
 5   # of Website Clicks  29 non-null     float64
 6   # of Searches        29 non-null     float64
 7   # of View Content    29 non-null     float64
 8   # of Add to Cart     29 non-null     float64
 9   # of Purchase        29 non-null     float64
dtypes: float64(7), int64(1), object(2)
memory usage: 2.5+ KB

In [13]:
df_test.head()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign Name        30 non-null     object
 1   Date                 30 non-null     object
 2   Spend [USD]          30 non-null     int64
 3   # of Impressions     30 non-null     int64
 4   Reach                30 non-null     int64
 5   # of Website Clicks  30 non-null     int64
 6   # of Searches        30 non-null     int64
 7   # of View Content    30 non-null     int64
 8   # of Add to Cart     30 non-null     int64
 9   # of Purchase        30 non-null     int64
dtypes: int64(8), object(2)
memory usage: 2.5+ KB

In [16]:
df_control['group'] = 'control'
df_test['group'] = 'treatment'

In [17]:
df = pd.concat([df_control, df_test], ignore_index=True)

## **Cleaning data**

In [18]:
df = df.dropna()

## **Execution**

In [19]:
df['conversion_rate'] = df['# of Purchase'] / df['# of Website Clicks']

In [20]:
df.groupby('group')['conversion_rate'].mean()

group
control      0.114772
treatment    0.092312
Name: conversion_rate, dtype: float64

## **Statistical Test (REAL A/B TEST)**

In [21]:
from scipy import stats

control = df[df['group'] == 'control']['conversion_rate']
treatment = df[df['group'] == 'treatment']['conversion_rate']

t_stat, p_value = stats.ttest_ind(control, treatment)

print("P-value:", p_value)

P-value: 0.13901844271836938

In [22]:
df.groupby('group')[['# of Purchase', '# of Website Clicks']].sum()

           # of Purchase  # of Website Clicks
group
control          15161.0             154303.0
treatment        15637.0             180970.0